<?php

/**
 * This file is part of the Cubiche/Metadata component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Core\Metadata\Tests\Units\Driver;

use Cubiche\Core\Metadata\Locator\DefaultFileLocator;
use Cubiche\Core\Metadata\Tests\Fixtures\Driver\XmlDriver;

/**
 * AbstractXmlDriverTests class.
 *
 * Generated by TestGenerator on 2017-05-16 at 13:17:21.
 */
class AbstractXmlDriverTests extends DriverTestCase
{
    /**
     * @return XmlDriver
     */
    protected function createDriver()
    {
        $mappingDirectory = __DIR__.'/../../Fixtures/mapping';

        return new XmlDriver(
            new DefaultFileLocator([
                $mappingDirectory => 'Cubiche\Core\Metadata\Tests',
            ])
        );
    }

    /**
     * Test loadMetadataForClass method.
     */
    public function testLoadMetadataForClass()
    {
        parent::testLoadMetadataForClass();

        $this
            ->given($driver = $this->createDriver())
            ->then()
                ->variable($driver->loadMetadataForClass('Cubiche\Foo\Bar\Tests\Blog'))
                    ->isNull()
                ->variable($driver->loadMetadataForClass('Address'))
                    ->isNull()
        ;
    }
}
