<?php

/**
 * This file is part of the Cubiche/Metadata component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Core\Metadata\Tests\Units\Driver;

use Cubiche\Core\Metadata\Driver\ChainDriver;
use Cubiche\Core\Metadata\Locator\DefaultFileLocator;
use Cubiche\Core\Metadata\Tests\Fixtures\Address;
use Cubiche\Core\Metadata\Tests\Fixtures\Driver\XmlDriver;
use Cubiche\Core\Metadata\Tests\Fixtures\Driver\YamlDriver;
use Cubiche\Core\Metadata\Tests\Fixtures\User;

/**
 * ChainDriverTests class.
 *
 * Generated by TestGenerator on 2017-05-16 at 13:17:21.
 */
class ChainDriverTests extends DriverTestCase
{
    /**
     * @return ChainDriver
     */
    protected function createDriver()
    {
        $mappingDirectory = __DIR__.'/../../Fixtures/mapping';

        $ymlDriver = new YamlDriver(
            new DefaultFileLocator([$mappingDirectory => 'Cubiche\Core\Metadata\Tests\Fixtures'])
        );

        $xmlDriver = new XmlDriver(
            new DefaultFileLocator([$mappingDirectory => 'Cubiche\Core\Metadata\Tests'])
        );

        return new ChainDriver([$ymlDriver, $xmlDriver]);
    }

    /**
     * @return ChainDriver
     */
    protected function createDriverWithDefaultDriver()
    {
        $mappingDirectory = __DIR__.'/../../Fixtures/mapping';

        $ymlDriver = new YamlDriver(
            new DefaultFileLocator([$mappingDirectory => 'Cubiche\Core\Metadata\Tests\Fixtures'])
        );

        return new ChainDriver([], $ymlDriver);
    }

    /**
     * @return ChainDriver
     */
    protected function createEmptyDriver()
    {
        return new ChainDriver();
    }

    /**
     * Test LoadMetadataForClass method.
     */
    public function testLoadMetadataForClass()
    {
        parent::testLoadMetadataForClass();

        $this
            ->given($driver = $this->createDriverWithDefaultDriver())
            ->when($classMetadata = $driver->loadMetadataForClass(User::class))
            ->then()
                ->array($classMetadata->propertiesMetadata())
                    ->hasSize(7)
                    ->hasKey('id')
                    ->hasKey('name')
                    ->hasKey('username')
                    ->hasKey('age')
                    ->hasKey('email')
                    ->hasKey('addresses')
                    ->hasKey('friends')
                ->object($propertyMetadata = $classMetadata->propertyMetadata('id'))
                    ->isNotNull()
                ->boolean($propertyMetadata->getMetadata('identifier'))
                    ->isTrue()
                ->string($propertyMetadata->getMetadata('name'))
                    ->isEqualTo('_id')
                ->string($classMetadata->propertyMetadata('name')->getMetadata('name'))
                    ->isEqualTo('fullName')
                ->string($classMetadata->propertyMetadata('addresses')->getMetadata('type'))
                    ->isEqualTo('ArraySet')
                ->string($classMetadata->propertyMetadata('addresses')->getMetadata('of'))
                    ->isEqualTo('Cubiche\Core\Metadata\Tests\Fixtures\Address')
        ;

        $this
            ->given($driver = $this->createEmptyDriver())
            ->then()
                ->variable($driver->loadMetadataForClass(User::class))
                    ->isNull()
        ;
    }

    /**
     * Test GetAllClassNames method.
     */
    public function testGetAllClassNames()
    {
        parent::testGetAllClassNames();

        $this
            ->given($driver = $this->createDriverWithDefaultDriver())
            ->when($classNames = $driver->getAllClassNames())
            ->then()
                ->array($classNames)
                    ->contains(User::class)
                    ->contains(Address::class)
                ->and()
                ->when($driver = $this->createEmptyDriver())
                ->then()
                    ->array($driver->getAllClassNames())
                        ->isEmpty()
        ;
    }
}
