<?php

/**
 * This file is part of the Cubiche/Metadata component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Core\Metadata\Tests\Units\Driver;

use Cubiche\Core\Metadata\Driver\MergeableDriver;
use Cubiche\Core\Metadata\Locator\DefaultFileLocator;
use Cubiche\Core\Metadata\Tests\Fixtures\Driver\XmlDriver;
use Cubiche\Core\Metadata\Tests\Fixtures\Driver\YamlDriver;

/**
 * MergeableDriverTests class.
 *
 * Generated by TestGenerator on 2017-05-16 at 13:17:21.
 */
class MergeableDriverTests extends DriverTestCase
{
    /**
     * @return MergeableDriver
     */
    protected function createDriver()
    {
        $mappingDirectory = __DIR__.'/../../Fixtures/mapping';

        $ymlDriver = new YamlDriver(
            new DefaultFileLocator([$mappingDirectory => 'Cubiche\Core\Metadata\Tests\Fixtures'])
        );

        $xmlDriver = new XmlDriver(
            new DefaultFileLocator([$mappingDirectory => 'Cubiche\Core\Metadata\Tests'])
        );

        return new MergeableDriver([$ymlDriver, $xmlDriver]);
    }
}
