<?php

/**
 * This file is part of the Cubiche/Metadata component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Core\Metadata\Tests\Units\Driver;

use Cubiche\Core\Metadata\Driver\StaticDriver;
use Cubiche\Core\Metadata\Exception\MappingException;
use Cubiche\Core\Metadata\Tests\Fixtures\Address;

/**
 * StaticDriverTests class.
 *
 * Generated by TestGenerator on 2017-05-16 at 13:17:21.
 */
class StaticDriverTests extends DriverTestCase
{
    /**
     * @return StaticDriver
     */
    protected function createDriver()
    {
        $driver = new StaticDriver('loadMetadata', [__DIR__.'/../../Fixtures']);
        $driver->addExcludePaths([
            __DIR__.'/../../Fixtures/Annotations',
            __DIR__.'/../../Fixtures/Driver',
            __DIR__.'/../../Fixtures/mapping',
            __DIR__.'/../../Fixtures/mapping-two',
        ]);
        $driver->setFileExtension('.php');

        return $driver;
    }

    /**
     * @return StaticDriver
     */
    protected function createEmptyDriver()
    {
        return new StaticDriver();
    }

    /**
     * @return StaticDriver
     */
    protected function createDriverWithInvalidPaths()
    {
        return new StaticDriver('loadMetadata', [__DIR__.'/../../Fixtures/Foo']);
    }

    /**
     * Test excludePaths method.
     */
    public function testExcludePaths()
    {
        $this
            ->given($driver = $this->createDriver())
            ->then()
                ->array($driver->excludePaths())
                    ->hasSize(4)
        ;
    }

    /**
     * Test loadMetadataForClass method.
     */
    public function testLoadMetadataForClass()
    {
        parent::testLoadMetadataForClass();

        $this
            ->given($driver = $this->createDriver())
            ->then()
                ->variable($driver->loadMetadataForClass(Address::class))
                    ->isNull()
                ->exception(function () use ($driver) {
                    $driver->loadMetadataForClass('Cubiche\Core\Metadata\Tests\Fixtures\City');
                })->isInstanceOf(MappingException::class)
                ->exception(function () use ($driver) {
                    $driver->loadMetadataForClass('Cubiche\Core\Metadata\Tests\Fixtures\UserId');
                })->isInstanceOf(MappingException::class)
        ;
    }

    /**
     * Test getAllClassNames method.
     */
    public function testGetAllClassNames()
    {
        parent::testGetAllClassNames();

        $this
            ->given($driver = $this->createDriver())
            ->when($classNames = $driver->getAllClassNames())
            ->and($classNames = $driver->getAllClassNames())
            ->then()
                ->array($classNames)
                    ->hasSize(5)
        ;

        $this
            ->given($driver = $this->createEmptyDriver())
            ->then()
                ->exception(function () use ($driver) {
                    $driver->getAllClassNames();
                })->isInstanceOf(MappingException::class);

        $this
            ->given($driver = $this->createDriverWithInvalidPaths())
            ->then()
                ->exception(function () use ($driver) {
                    $driver->getAllClassNames();
                })->isInstanceOf(MappingException::class);
    }
}
