<?php

/**
 * This file is part of the Cubiche package.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Core\Cqrs\Tests\Units\Middlewares\Handler\Resolver\NameOfQuery;

use Cubiche\Core\Cqrs\Middlewares\Handler\Resolver\NameOfQuery\FromClassNameResolver;
use Cubiche\Core\Cqrs\Tests\Fixtures\Query\PublishedPostsQuery;
use Cubiche\Core\Cqrs\Tests\Units\TestCase;

/**
 * FromClassNameResolver class.
 *
 * Generated by TestGenerator on 2016-04-07 at 15:40:41.
 */
class FromClassNameResolverTests extends TestCase
{
    /**
     * Test Resolve method.
     */
    public function testResolve()
    {
        $this
            ->given($resolver = new FromClassNameResolver())
            ->when($result = $resolver->resolve(new PublishedPostsQuery(new \DateTime())))
            ->then()
                ->string($result)
                    ->isEqualTo(PublishedPostsQuery::class)
        ;
    }
}
