<?php
/**
 * This file is part of the Cubiche package.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Core\Cqrs\Tests\Units\Middlewares\Handler\Resolver\NameOfCommand;

use Cubiche\Core\Bus\Exception\NotFoundException;
use Cubiche\Core\Cqrs\Middlewares\Handler\Resolver\NameOfCommand\ChainResolver;
use Cubiche\Core\Cqrs\Middlewares\Handler\Resolver\NameOfCommand\FromClassNameResolver;
use Cubiche\Core\Cqrs\Middlewares\Handler\Resolver\NameOfCommand\FromCommandNamedResolver;
use Cubiche\Core\Cqrs\Tests\Fixtures\Command\LoginUserCommand;
use Cubiche\Core\Cqrs\Tests\Fixtures\Command\LogoutUserCommand;
use Cubiche\Core\Cqrs\Tests\Units\TestCase;

/**
 * ChainResolver class.
 *
 * Generated by TestGenerator on 2016-04-07 at 15:40:41.
 */
class ChainResolverTests extends TestCase
{
    /**
     * Test Resolve method.
     */
    public function testResolve()
    {
        $this
            ->given($resolver1 = new FromCommandNamedResolver())
            ->and($resolver2 = new FromClassNameResolver())
            ->and($resolver = new ChainResolver([$resolver1, $resolver2]))
            ->when($result = $resolver->resolve(new LoginUserCommand('ivan@cubiche.com', 'plainpassword')))
            ->then()
                ->string($result)
                    ->isEqualTo(LoginUserCommand::class)
            ->and()
            ->when($result = $resolver->resolve(new LogoutUserCommand('ivan@cubiche.com')))
            ->then()
                ->string($result)
                    ->isEqualTo('logout_user')
        ;

        $this
            ->given($resolver = new ChainResolver([]))
            ->then()
                ->exception(function () use ($resolver) {
                    $resolver->resolve(new LogoutUserCommand('ivan@cubiche.com'));
                })
                ->isInstanceOf(NotFoundException::class)
        ;
    }
}
