<?php
/**
 * This file is part of the Cubiche package.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace V1_1_0;

use Cubiche\Domain\EventSourcing\EventStore\EventStream;
use Cubiche\Domain\EventSourcing\Migrations\MigrationInterface;

/**
 * BlogEventSourcedMigration class.
 *
 * Generated by MigrationGenerator on 2016-08-31 at 15:47:45.
 */
class BlogEventSourcedMigration implements MigrationInterface
{
    /**
     * {@inheritdoc}
     */
    public function migrate(EventStream $eventStream)
    {
        // TODO: Implement migrate() method.
        return $eventStream;
    }

    /**
     * {@inheritdoc}
     */
    public function aggregateClassName()
    {
        return \BlogEventSourced::class;
    }
}
