language: php
sudo: false
php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm
install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
script:
  - mkdir -p build/logs
  - bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - travis_retry sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php bin/coveralls -v; fi;'
  