language: php
sudo: false
php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm
install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
before_script:
  - "[ -n \"$COVERALLS_REPO_TOKEN\" ] && sed -i s/YouCoverallsProjectToken/$COVERALLS_REPO_TOKEN/ .atoum.travis.php || true"
script:
  - bin/atoum -c .atoum.travis.php +verbose
  