<?php

/**
 * This file is part of the Cubiche/EventSourcing component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Domain\EventSourcing\Tests\Units\Versioning;

use Cubiche\Domain\EventSourcing\Versioning\InMemoryVersionStore;

/**
 * InMemoryVersionStoreTests class.
 *
 * Generated by TestGenerator on 2016-07-29 at 12:24:22.
 */
class InMemoryVersionStoreTests extends VersionStoreTestCase
{
    /**
     * {@inheritdoc}
     */
    protected function createStore()
    {
        return new InMemoryVersionStore();
    }
}
