<?php

/**
 * This file is part of the Cubiche/EventSourcing component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Domain\EventSourcing\Tests\Units\Versioning;

use Cubiche\Domain\EventSourcing\Tests\Fixtures\PostEventSourcedFactory;
use Cubiche\Domain\EventSourcing\Tests\Units\TestCase;
use Cubiche\Domain\EventSourcing\Versioning\InMemoryVersionStore;
use Cubiche\Domain\EventSourcing\Versioning\VersionManager;

/**
 * VersionManagerTests class.
 *
 * Generated by TestGenerator on 2016-06-28 at 14:36:54.
 */
class VersionManagerTests extends TestCase
{
    /**
     * Test testVersionOf method.
     */
    public function testVersionOf()
    {
        $this
            ->given(
                $post = PostEventSourcedFactory::create(
                    $this->faker->sentence,
                    $this->faker->paragraph
                )
            )
            ->and($version = VersionManager::versionOf($post))
            ->then()
                ->integer($version)
                    ->isEqualTo(0)
        ;
    }

    /**
     * Test SetVersionStore method.
     */
    public function testSetVersionStore()
    {
        $this
            ->given($manager = VersionManager::create())
            ->when($manager->setVersionStore(new InMemoryVersionStore()))
            ->then()
                ->boolean(true)
                    ->isTrue()
        ;
    }

    /**
     * Test persistVersionOf method.
     */
    public function testPersistVersionOf()
    {
        $this
            ->given(
                $post = PostEventSourcedFactory::create(
                    $this->faker->sentence,
                    $this->faker->paragraph
                )
            )
            ->and($version = VersionManager::versionOf($post))
            ->then()
                ->integer($version)
                    ->isEqualTo(0)
                ->and()
                ->when($post->setVersion(23))
                ->and(VersionManager::persistVersionOf($post))
                ->then()
                    ->integer(VersionManager::versionOf($post))
                        ->isEqualTo(23)
        ;
    }
}
