<?php

/**
 * This file is part of the Cubiche/EventSourcing component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Domain\EventSourcing\Tests\Units\Versioning;

use Cubiche\Domain\EventSourcing\Tests\Units\TestCase;

/**
 * VersionTests class.
 *
 * Generated by TestGenerator on 2016-06-28 at 14:36:54.
 */
class VersionTests extends TestCase
{
    /**
     * Test ModelVersion method.
     */
    public function testModelVersion()
    {
        // todo: Implement testModelVersion().
    }

    /**
     * Test SetModelVersion method.
     */
    public function testSetModelVersion()
    {
        // todo: Implement testSetModelVersion().
    }

    /**
     * Test IncModelVersion method.
     */
    public function testIncModelVersion()
    {
        // todo: Implement testIncModelVersion().
    }

    /**
     * Test AggregateVersion method.
     */
    public function testAggregateVersion()
    {
        // todo: Implement testAggregateVersion().
    }

    /**
     * Test SetAggregateVersion method.
     */
    public function testSetAggregateVersion()
    {
        // todo: Implement testSetAggregateVersion().
    }

    /**
     * Test IncAggregateVersion method.
     */
    public function testIncAggregateVersion()
    {
        // todo: Implement testIncAggregateVersion().
    }
}
