<?php

/**
 * This file is part of the Cubiche package.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Core\Bus\Tests\Units\Middlewares\Handler\Resolver\HandlerMethodName;

use Cubiche\Core\Bus\Middlewares\Handler\Resolver\HandlerMethodName\MethodWithShortObjectNameResolver;
use Cubiche\Core\Bus\Tests\Fixtures\Command\LoginUserCommand;
use Cubiche\Core\Bus\Tests\Fixtures\Query\PublishedPostsQuery;
use Cubiche\Core\Bus\Tests\Units\TestCase;

/**
 * MethodWithShortObjectNameResolver class.
 *
 * Generated by TestGenerator on 2016-04-07 at 15:40:41.
 */
class MethodWithShortObjectNameResolverTests extends TestCase
{
    /**
     * Test Resolve method.
     */
    public function testResolve()
    {
        $this
            ->given($resolver = new MethodWithShortObjectNameResolver('Command'))
            ->when($result = $resolver->resolve(LoginUserCommand::class))
            ->then()
                ->string($result)
                    ->isEqualTo('loginUser')
        ;

        $this
            ->given($resolver = new MethodWithShortObjectNameResolver('Query'))
            ->when($result = $resolver->resolve(PublishedPostsQuery::class))
            ->then()
                ->string($result)
                    ->isEqualTo('publishedPosts')
        ;

        $this
            ->given($resolver = new MethodWithShortObjectNameResolver('Service'))
            ->when($result = $resolver->resolve(LoginUserCommand::class))
            ->then()
                ->string($result)
                    ->isEqualTo('loginUserCommand')
        ;
    }
}
