<?php

/**
 * This file is part of the Cubiche/EventSourcing component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Domain\EventSourcing\Tests\Units;

use Cubiche\Core\Bus\MessageId;
use Cubiche\Domain\EventSourcing\Tests\Fixtures\Event\PostWasCreated;
use Cubiche\Domain\EventSourcing\Tests\Fixtures\PostId;

/**
 * DomainEventTests class.
 *
 * Generated by TestGenerator on 2016-06-28 at 14:36:54.
 */
class DomainEventTests extends TestCase
{
    /**
     * Test id method.
     */
    public function testId()
    {
        $this
            ->given($postId = PostId::next())
            ->when(
                $event = new PostWasCreated(
                    $postId,
                    $this->faker->sentence,
                    $this->faker->paragraph
                )
            )
            ->then()
                ->object($event->messageId())
                    ->isInstanceOf(MessageId::class)
        ;
    }

    /**
     * Test AggregateId method.
     */
    public function testAggregateId()
    {
        $this
            ->given($postId = PostId::next())
            ->when(
                $event = new PostWasCreated(
                    $postId,
                    $this->faker->sentence,
                    $this->faker->paragraph
                )
            )
            ->then()
                ->string($event->aggregateId()->toNative())
                    ->isEqualTo($postId->toNative())
        ;
    }

    /**
     * Test Version method.
     */
    public function testVersion()
    {
        $this
            ->given($postId = PostId::next())
            ->when(
                $event = new PostWasCreated(
                    $postId,
                    $this->faker->sentence,
                    $this->faker->paragraph
                )
            )
            ->then()
                ->integer($event->version())
                    ->isEqualTo(0)
                ->and()
                ->when($event->setVersion(165))
                ->then()
                    ->integer($event->version())
                        ->isEqualTo(165)
        ;
    }
}
