<?php

/**
 * This file is part of the Cubiche/EventSourcing component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Domain\EventSourcing\Tests\Units;

/**
 * DomainEventTests class.
 *
 * Generated by TestGenerator on 2016-06-28 at 14:36:54.
 */
class DomainEventTests extends TestCase
{
    /**
     * Test AggregateId method.
     */
    public function testAggregateId()
    {
        // todo: Implement testAggregateId().
    }

    /**
     * Test Version method.
     */
    public function testVersion()
    {
        // todo: Implement testVersion().
    }

    /**
     * Test SetVersion method.
     */
    public function testSetVersion()
    {
        // todo: Implement testSetVersion().
    }
}
