<?php

/**
 * This file is part of the Cubiche/EventSourcing component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Domain\EventSourcing\Tests\Units;

/**
 * EventSourcedAggregateRepositoryTests class.
 *
 * Generated by TestGenerator on 2016-06-28 at 14:36:54.
 */
class EventSourcedAggregateRepositoryTests extends TestCase
{
    /**
     * Test Get method.
     */
    public function testGet()
    {
        // todo: Implement testGet().
    }

    /**
     * Test Persist method.
     */
    public function testPersist()
    {
        // todo: Implement testPersist().
    }

    /**
     * Test PersistAll method.
     */
    public function testPersistAll()
    {
        // todo: Implement testPersistAll().
    }

    /**
     * Test Remove method.
     */
    public function testRemove()
    {
        // todo: Implement testRemove().
    }
}
