<?php

/**
 * This file is part of the Cubiche/EventBus component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Core\EventBus\Tests\Units;

use Cubiche\Core\EventBus\Notifier;
use Cubiche\Core\EventBus\Event;
use Cubiche\Core\EventBus\EventInterface;
use Cubiche\Core\EventBus\Tests\Fixtures\InvalidEvent;
use Cubiche\Core\EventBus\Tests\Fixtures\LoginUserEvent;
use Cubiche\Core\EventBus\Tests\Fixtures\LoginUserEventListener;
use Cubiche\Core\EventBus\Tests\Fixtures\UserEventSubscriber;

/**
 * Notifier class.
 *
 * Generated by TestGenerator on 2016-04-11 at 15:18:25.
 */
class NotifierTests extends TestCase
{
    /**
     * @return Notifier
     */
    public function createNotifier()
    {
        return new Notifier();
    }

    /**
     * Test Notify method.
     */
    public function testNotify()
    {
        // notify event name
        $this
            ->given($notifier = $this->createNotifier())
            ->when($event = $notifier->notify('foo.event'))
            ->then()
                ->object($event)
                    ->isInstanceOf(Event::class)
        ;

        // notify event named
        $this
            ->given($notifier = $this->createNotifier())
            ->when($event = $notifier->notify(Event::named('foo.event')))
            ->then()
                ->object($event)
                    ->isInstanceOf(Event::class)
        ;

        // notify event class
        $this
            ->given($notifier = $this->createNotifier())
            ->when($event = $notifier->notify(new LoginUserEvent('ivan@cubiche.com')))
            ->then()
                ->object($event)
                    ->isInstanceOf(EventInterface::class)
        ;

        // notify invalid event
        $this
            ->given($notifier = $this->createNotifier())
            ->then()
                ->exception(function () use ($notifier) {
                    $notifier->notify(new InvalidEvent());
                })
                ->isInstanceOf(\InvalidArgumentException::class)
        ;

        // notify with one callable listener
        $this
            ->given($notifier = $this->createNotifier())
            ->and($counter = 0)
            ->and($notifier->addListener('foo.event', function (Event $event) use (&$counter) {
                ++$counter;
            }))
            ->when($notifier->notify('foo.event'))
            ->then()
                ->integer($counter)
                    ->isEqualTo(1)
        ;

        // notify with many callable listener
        $this
            ->given($notifier = $this->createNotifier())
            ->and($counter = 0)
            ->and($notifier->addListener('foo.event', function (Event $event) use (&$counter) {
                ++$counter;
            }))
            ->and($notifier->addListener('foo.event', function (Event $event) use (&$counter) {
                ++$counter;
            }))
            ->when($notifier->notify('foo.event'))
            ->then()
                ->integer($counter)
                    ->isEqualTo(2)
        ;

        // notify with many callable listener but stopped the event propagation
        $this
            ->given($notifier = $this->createNotifier())
            ->and($counter = 0)
            ->and($notifier->addListener('foo.event', function (Event $event) use (&$counter) {
                ++$counter;
                $event->stopPropagation();
            }))
            ->and($notifier->addListener('foo.event', function (Event $event) use (&$counter) {
                ++$counter;
            }))
            ->when($notifier->notify('foo.event'))
            ->then()
                ->integer($counter)
                    ->isEqualTo(1)
        ;

        // notify with many callable listener and priority
        $this
            ->given($notifier = $this->createNotifier())
            ->and($counter = 3)
            ->and($notifier->addListener('foo.event', function (Event $event) use (&$counter) {
                $counter = $counter * 5;
            }, 50))
            ->and($notifier->addListener('foo.event', function (Event $event) use (&$counter) {
                $counter = $counter + 2;
            }, 100))
            ->when($notifier->notify('foo.event'))
            ->then()
                ->integer($counter)
                    ->isEqualTo(25)
        ;

        // notify with many listener class or callable
        $this
            ->given($notifier = $this->createNotifier())
            ->and($event = new LoginUserEvent('ivan@cubiche.com'))
            ->and($notifier->addListener($event->name(), array(new LoginUserEventListener(), 'onLogin')))
            ->and($notifier->addListener($event->name(), function (LoginUserEvent $event) {
                $this
                    ->string($event->email())
                        ->isEqualTo('info@cubiche.org')
                ;

                $event->setEmail('fake@email.com');
            }))
            ->when($notifier->notify($event))
            ->then()
                ->string($event->email())
                    ->isEqualTo('fake@email.com')
        ;
    }

    /**
     * Test listeners method.
     */
    public function testListeners()
    {
        $this
            ->given($notifier = $this->createNotifier())
            ->and($notifier->addListener('event.foo', array(new LoginUserEventListener(), 'onLogin')))
            ->and($notifier->addListener('event.foo', function (Event $event) {

            }))
            ->and($notifier->addListener('event.bar', function (Event $event) {

            }))
            ->when($listeners = $notifier->listeners())
                ->then()
                    ->array($listeners->toArray())
                        ->hasKey('event.foo')
                        ->hasKey('event.bar')
                    ->array($listeners->toArray())
                        ->hasSize(2)
                    ->array($listeners->toArray())
                        ->array['event.foo']
                            ->hasSize(2)
        ;
    }

    /**
     * Test listenerPriority method.
     */
    public function testListenerPriority()
    {
        $this
            ->given($notifier = $this->createNotifier())
            ->and($listener1 = array(new LoginUserEventListener(), 'onLogin'))
            ->and($listener2 = function (Event $event) {
                return $event->name();
            })
            ->and($listener3 = function (Event $event) {

            })
            ->and($notifier->addListener('event.foo', $listener1, 100))
            ->and($notifier->addListener('event.foo', $listener2, 50))
            ->and($notifier->addListener('event.bar', $listener3))
            ->then()
                ->variable($notifier->listenerPriority('event.unknow', $listener1))
                    ->isNull()
                ->variable($notifier->listenerPriority('event.foo', $listener3))
                    ->isNull()
                ->integer($notifier->listenerPriority('event.foo', $listener1))
                    ->isEqualTo(100)
                ->integer($notifier->listenerPriority('event.foo', $listener2))
                    ->isEqualTo(50)
        ;
    }

    /**
     * Test HasListeners method.
     */
    public function testHasListeners()
    {
        $this
            ->given($notifier = $this->createNotifier())
            ->and($listener1 = array(new LoginUserEventListener(), 'onLogin'))
            ->and($listener2 = function (Event $event) {
                return $event->name();
            })
            ->and($listener3 = function (Event $event) {

            })
            ->and($notifier->addListener('event.foo', $listener1, 100))
            ->and($notifier->addListener('event.foo', $listener2, 50))
            ->and($notifier->addListener('event.bar', $listener3))
            ->then()
                ->boolean($notifier->hasListeners('event.unknow'))
                    ->isFalse()
                ->boolean($notifier->hasListeners('event.foo'))
                    ->isTrue()
                ->boolean($notifier->hasListeners())
                    ->isTrue()
        ;
    }

    /**
     * Test RemoveListener method.
     */
    public function testRemoveListener()
    {
        $this
            ->given($notifier = $this->createNotifier())
            ->and($listener1 = array(new LoginUserEventListener(), 'onLogin'))
            ->and($listener2 = function (Event $event) {
                return $event->name();
            })
            ->and($listener3 = function (Event $event) {

            })
            ->and($notifier->addListener('event.foo', $listener1, 100))
            ->and($notifier->addListener('event.foo', $listener2, 50))
            ->and($notifier->addListener('event.bar', $listener3))
            ->then()
                ->boolean($notifier->hasListeners('event.foo'))
                    ->isTrue()
                ->and()
                ->when($notifier->removeListener('event.foo', $listener1))
                ->then()
                    ->boolean($notifier->hasListeners('event.foo'))
                        ->isTrue()
                ->and()
                ->when($notifier->removeListener('event.unknow', $listener2))
                ->when($notifier->removeListener('event.foo', $listener2))
                ->then()
                    ->boolean($notifier->hasListeners('event.foo'))
                        ->isFalse()
        ;
    }

    /**
     * Test AddSubscriber method.
     */
    public function testAddSubscriber()
    {
        $this
            ->given($notifier = $this->createNotifier())
            ->and($notifier->addSubscriber(new UserEventSubscriber()))
            ->then()
                ->boolean($notifier->hasListeners())
                    ->isTrue()
                ->boolean($notifier->hasListeners(UserEventSubscriber::FOO_EVENT))
                    ->isTrue()
                ->boolean($notifier->hasListeners(UserEventSubscriber::BAR_EVENT))
                    ->isTrue()
                ->boolean($notifier->hasListeners(UserEventSubscriber::USER_LOGIN))
                    ->isTrue()
        ;
    }

    /**
     * Test RemoveSubscriber method.
     */
    public function testRemoveSubscriber()
    {
        $this
            ->given($notifier = $this->createNotifier())
            ->and($subscriber = new UserEventSubscriber())
            ->and($notifier->addSubscriber($subscriber))
            ->then()
                ->boolean($notifier->hasListeners(UserEventSubscriber::FOO_EVENT))
                    ->isTrue()
                ->boolean($notifier->hasListeners(UserEventSubscriber::BAR_EVENT))
                    ->isTrue()
                ->boolean($notifier->hasListeners(UserEventSubscriber::USER_LOGIN))
                    ->isTrue()
                ->and()
                ->when($notifier->removeSubscriber($subscriber))
                ->then()
                    ->boolean($notifier->hasListeners(UserEventSubscriber::FOO_EVENT))
                        ->isFalse()
                    ->boolean($notifier->hasListeners(UserEventSubscriber::BAR_EVENT))
                        ->isFalse()
                    ->boolean($notifier->hasListeners(UserEventSubscriber::USER_LOGIN))
                        ->isFalse()
        ;
    }
}
