language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - MONGO_DRIVER=mongodb

matrix:
  include:
    - php: 7.1
      env:
        - DRIVER_VERSION=1.3.3

services: mongodb

before_install:
  - yes '' | pecl -q install -f $MONGO_DRIVER-${DRIVER_VERSION}
  - php --ri $MONGO_DRIVER
  - travis_retry composer self-update

install:
  - travis_retry composer global require "hirak/prestissimo:^0.3"
  - travis_retry composer install $COMPOSER_ARGS

script:
  - vendor/bin/atoum -c .atoum.travis.php +verbose