<?php

/**
 * This file is part of the Cubiche/Locale component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Domain\Locale\Tests\Units;

use Cubiche\Domain\Locale\LanguageCode;

/**
 * LanguageCodeTests class.
 *
 * Generated by TestGenerator on 2018-01-15 at 13:40:07.
 */
class LanguageCodeTests extends TestCase
{
    /**
     * Test fromNative method.
     */
    public function testFromNative()
    {
        $this
            ->given($languageCode = LanguageCode::fromNative('as'))
            ->then()
                ->boolean($languageCode->equals(LanguageCode::AS()))
                    ->isTrue()
                ->and()
                ->when($languageCode = LanguageCode::fromNative('OR'))
                ->then()
                    ->boolean($languageCode->equals(LanguageCode::OR()))
                        ->isTrue()
        ;
    }
}
