<?php

/**
 * This file is part of the Cubiche/Locale component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Domain\Locale\Tests\Units;

use Cubiche\Domain\Locale\LocaleCode;

/**
 * LocaleCodeTests class.
 *
 * Generated by TestGenerator on 2018-01-15 at 13:40:07.
 */
class LocaleCodeTests extends TestCase
{
    /**
     * Test fromNative method.
     */
    public function testFromNative()
    {
        $this
            ->given($languageCode = LocaleCode::fromNative('en_NZ'))
            ->then()
                ->boolean($languageCode->equals(LocaleCode::EN_NZ()))
                    ->isTrue()
                ->and()
                ->when($languageCode = LocaleCode::fromNative('be'))
                ->then()
                    ->boolean($languageCode->equals(LocaleCode::BE()))
                        ->isTrue()
        ;
    }
}
