<?php

/**
 * This file is part of the Cubiche/Locale component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Domain\Locale\Tests\Units;

use Cubiche\Tests\TestCase as BaseTestCase;

/**
 * TestCase class.
 *
 * Generated by TestGenerator on 2018-01-15 at 13:40:07.
 */
abstract class TestCase extends BaseTestCase
{
}
