<?php

/**
 * This file is part of the Cubiche/Storage component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Infrastructure\Storage\Tests\Units;

use Cubiche\Core\Storage\StorageInterface;
use Cubiche\Core\Storage\Tests\Units\StorageTestCase;
use Cubiche\Infrastructure\Storage\SessionStorage;
use Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBag;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\Session\Storage\MockArraySessionStorage;

/**
 * SessionStorageTests class.
 *
 * Generated by TestGenerator on 2017-05-03 at 11:41:18.
 */
class SessionStorageTests extends StorageTestCase
{
    /**
     * @return StorageInterface
     */
    protected function createStorage()
    {
        $session = new Session(new MockArraySessionStorage(), new AttributeBag(), new FlashBag());

        return new SessionStorage($session);
    }
}
