<?php

/**
 * This file is part of the Cubiche package.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Core\EventDispatcher\Tests\Units;

use Cubiche\Core\EventDispatcher\DelegateListener;

/**
 * DelegateListener class.
 *
 * Generated by TestGenerator on 2016-04-12 at 18:44:36.
 */
class DelegateListenerTests extends TestCase
{
    /**
     * Test Callback method.
     */
    public function testCallback()
    {
        $this
            ->given($listener = array($this, 'testEquals'))
            ->and($delegate = new DelegateListener($listener))
            ->then()
                ->array($delegate->callback())
                    ->isEqualTo($listener)
        ;
    }

    /**
     * Test Equals method.
     */
    public function testEquals()
    {
        $this
            ->given($listener = array($this, 'testEquals'))
            ->and($delegate = new DelegateListener($listener))
            ->then()
                ->boolean($delegate->equals($listener))
                    ->isTrue()
                ->boolean($delegate->equals($delegate))
                    ->isTrue()
        ;
    }
}
