<?php

/**
 * This file is part of the Cubiche package.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Core\EventDispatcher\Tests\Units;

use Cubiche\Tests\TestCase as BaseTestCase;

/**
 * TestCase class.
 *
 * Generated by TestGenerator on 2016-04-11 at 15:18:25.
 */
abstract class TestCase extends BaseTestCase
{
}
