<?php

/**
 * This file is part of the Cubiche/Metadata component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Infrastructure\MongoDB\Tests\Units\Metadata\Driver;

use Cubiche\Core\Metadata\ClassMetadata;
use Cubiche\Core\Metadata\Driver\DriverInterface;
use Cubiche\Core\Metadata\Exception\MappingException;
use Cubiche\Core\Metadata\Tests\Units\TestCase;
use Cubiche\Infrastructure\MongoDB\Tests\Fixtures\Metadata\Address;
use Cubiche\Infrastructure\MongoDB\Tests\Fixtures\Metadata\User;

/**
 * DriverTestCase class.
 *
 * Generated by TestGenerator on 2017-05-16 at 13:17:21.
 */
abstract class DriverTestCase extends TestCase
{
    /**
     * @return DriverInterface
     */
    abstract protected function createDriver();

    /**
     * Test loadMetadataForClass method.
     */
    public function testLoadMetadataForClass()
    {
        $this
            ->given($driver = $this->createDriver())
            ->then()
                ->exception(function () use ($driver) {
                    $driver->loadMetadataForClass('Cubiche\Infrastructure\MongoDB\Tests\Fixtures\Metadata\Post');
                })->isInstanceOf(MappingException::class)
                ->exception(function () use ($driver) {
                    $driver->loadMetadataForClass('Cubiche\Infrastructure\MongoDB\Tests\Fixtures\Metadata\Blog');
                })->isInstanceOf(MappingException::class)
        ;

        $this
            ->given($driver = $this->createDriver())
            ->when($classMetadata = $driver->loadMetadataForClass(User::class))
            ->then()
                ->object($classMetadata)
                    ->isInstanceOf(ClassMetadata::class)
                ->array($classMetadata->propertiesMetadata())
                    ->hasSize(7)
                    ->hasKey('id')
                    ->hasKey('name')
                    ->hasKey('username')
                    ->hasKey('age')
                    ->hasKey('email')
                    ->hasKey('addresses')
                    ->hasKey('friends')
                ->object($propertyMetadata = $classMetadata->propertyMetadata('id'))
                    ->isNotNull()
                ->boolean($propertyMetadata->getMetadata('identifier'))
                    ->isTrue()
                ->string($propertyMetadata->getMetadata('name'))
                    ->isEqualTo('_id')
                ->string($classMetadata->propertyMetadata('name')->getMetadata('name'))
                    ->isEqualTo('fullName')
                ->string($classMetadata->propertyMetadata('addresses')->getMetadata('type'))
                    ->isEqualTo('ArrayList[Cubiche\Infrastructure\MongoDB\Tests\Fixtures\Metadata\Address]')
                ->string($classMetadata->propertyMetadata('friends')->getMetadata('type'))
                    ->isEqualTo('ArraySet[Cubiche\Infrastructure\MongoDB\Tests\Fixtures\Metadata\User]')
            ->and()
            ->when($classMetadata = $driver->loadMetadataForClass(User::class))
            ->then()
                ->object($classMetadata)
                    ->isInstanceOf(ClassMetadata::class)
        ;
    }

    /**
     * Test getAllClassNames method.
     */
    public function testGetAllClassNames()
    {
        $this
            ->given($driver = $this->createDriver())
            ->when($classNames = $driver->getAllClassNames())
            ->then()
                ->array($classNames)
                    ->contains(User::class)
                    ->contains(Address::class)
        ;
    }
}
