<?php

/**
 * This file is part of the Cubiche/Metadata component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Infrastructure\MongoDB\Tests\Units\Metadata\Driver;

use Cubiche\Core\Metadata\Locator\DefaultFileLocator;
use Cubiche\Infrastructure\MongoDB\Metadata\Driver\XmlDriver;
use Cubiche\Infrastructure\MongoDB\Tests\Fixtures\Metadata\AddressId;

/**
 * XmlDriverTests class.
 *
 * Generated by TestGenerator on 2017-05-16 at 13:17:21.
 */
class XmlDriverTests extends DriverTestCase
{
    /**
     * @return XmlDriver
     */
    protected function createDriver()
    {
        $mappingDirectory = __DIR__.'/../../../Fixtures/Metadata/mapping';

        return new XmlDriver(
            new DefaultFileLocator([
                $mappingDirectory => 'Cubiche\Infrastructure\MongoDB\Tests\Fixtures\Metadata',
            ])
        );
    }

    /**
     * Test loadMetadataForClass method.
     */
    public function testLoadMetadataForClass()
    {
        parent::testLoadMetadataForClass();

        $this
            ->given($driver = $this->createDriver())
            ->then()
                ->exception(function () use ($driver) {
                    $driver->loadMetadataForClass(AddressId::class);
                })->isInstanceOf(\InvalidArgumentException::class)
                ->variable($driver->loadMetadataForClass('Cubiche\Foo\Bar\Tests\Blog'))
                    ->isNull()
                ->variable($driver->loadMetadataForClass('Address'))
                    ->isNull()
        ;
    }
}
