<?php

/**
 * This file is part of the Cubiche/EventSourcing component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Domain\EventSourcing\Tests\Units\Migrations\Cli\Command;

use Cubiche\Domain\EventSourcing\Migrations\Cli\Command\MigrationsGenerateCommand;
use Cubiche\Domain\EventSourcing\Tests\Fixtures\PostEventSourced;
use Cubiche\Domain\EventSourcing\Tests\Units\TestCase;

/**
 * MigrationsGenerateCommandTests class.
 *
 * Generated by TestGenerator on 2016-08-10 at 10:18:25.
 */
class MigrationsGenerateCommandTests extends TestCase
{
    /**
     * Test Version method.
     */
    public function testVersion()
    {
        $this
            ->given($command = new MigrationsGenerateCommand())
            ->then()
                ->variable($command->version())
                    ->isNull()
                ->variable($command->aggregate())
                    ->isNull()
        ;
    }

    /**
     * Test SetVersion method.
     */
    public function testSetVersion()
    {
        $this
            ->given($command = new MigrationsGenerateCommand())
            ->when($command->setVersion('4.5.0'))
            ->then()
                ->string($command->version())
                    ->isEqualTo('4.5.0')
        ;
    }

    /**
     * Test SetAggregate method.
     */
    public function testSetAggregate()
    {
        $this
            ->given($command = new MigrationsGenerateCommand())
            ->when($command->setAggregate(PostEventSourced::class))
            ->then()
                ->string($command->aggregate())
                    ->isEqualTo(PostEventSourced::class)
        ;
    }
}
