<?php

/**
 * This file is part of the Cubiche/Command component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Domain\CommandBus\Tests\Units\Middlewares\Handler\Resolver\CommandName;

use Cubiche\Domain\CommandBus\Middlewares\Handler\Resolver\CommandName\FromCommandResolver;
use Cubiche\Domain\CommandBus\Tests\Fixtures\LoginUserCommand;
use Cubiche\Domain\CommandBus\Tests\Fixtures\LogoutUserCommand;
use Cubiche\Domain\CommandBus\Tests\Units\TestCase;

/**
 * FromCommandResolver class.
 *
 * Generated by TestGenerator on 2016-04-07 at 15:40:41.
 */
class FromCommandResolverTests extends TestCase
{
    /**
     * Test Resolve method.
     */
    public function testResolve()
    {
        $this
            ->given($resolver = new FromCommandResolver())
            ->when($result = $resolver->resolve(new LogoutUserCommand('ivan@cubiche.com')))
            ->then()
                ->string($result)
                    ->isEqualTo('logout_user')
        ;

        $this
            ->given($resolver = new FromCommandResolver())
            ->then()
                ->exception(function () use ($resolver) {
                    $resolver->resolve(new LoginUserCommand('ivan@cubiche.com', 'plainpassword'));
                })
                ->isInstanceOf(\InvalidArgumentException::class)
        ;
    }
}
