<?php

/**
 * This file is part of the Cubiche/Command component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Domain\Command\Tests\Units\Middlewares\Handler\Resolver\MethodName;

use Cubiche\Domain\Command\Exception\InvalidResolverException;
use Cubiche\Domain\Command\Exception\NotFoundException;
use Cubiche\Domain\Command\Middlewares\Handler\Resolver\MethodName\ChainResolver;
use Cubiche\Domain\Command\Middlewares\Handler\Resolver\MethodName\DefaultResolver;
use Cubiche\Domain\Command\Middlewares\Handler\Resolver\MethodName\MethodWithShortCommandNameResolver;
use Cubiche\Domain\Command\Tests\Fixtures\InvalidMethodNameResolver;
use Cubiche\Domain\Command\Tests\Fixtures\LoginUserCommand;
use Cubiche\Domain\Command\Tests\Fixtures\LogoutUserCommand;
use Cubiche\Domain\Command\Tests\Units\TestCase;

/**
 * ChainResolver class.
 *
 * Generated by TestGenerator on 2016-04-07 at 15:40:41.
 */
class ChainResolverTests extends TestCase
{
    /**
     * Test create.
     */
    public function testCreate()
    {
        $this
            ->given($resolver1 = new \StdClass())
            ->then()
            ->exception(function () use ($resolver1) {
                new ChainResolver([$resolver1]);
            })
            ->isInstanceOf(InvalidResolverException::class)
        ;
    }

    /**
     * Test Resolve method.
     */
    public function testResolve()
    {
        $this
            ->given($resolver1 = new InvalidMethodNameResolver())
            ->and($resolver2 = new MethodWithShortCommandNameResolver())
            ->and($resolver3 = new DefaultResolver())
            ->and($resolver = new ChainResolver([$resolver1, $resolver2, $resolver3]))
            ->when($result = $resolver->resolve(new LoginUserCommand('ivan@timeout.com', 'plainpassword')))
            ->then()
                ->string($result)
                    ->isEqualTo('handleLoginUser')
        ;

        $this
            ->given($resolver = new ChainResolver([]))
            ->then()
            ->exception(function () use ($resolver) {
                $resolver->resolve(new LogoutUserCommand('ivan@timeout.com'));
            })
            ->isInstanceOf(NotFoundException::class)
        ;
    }
}
