<?php

/**
 * This file is part of the Cubiche package.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Core\Bus\Tests\Units\Middlewares\Validator;

use Cubiche\Core\Bus\Middlewares\Validator\ValidatorMiddleware;
use Cubiche\Core\Bus\Tests\Fixtures\Command\LoginUserCommand;
use Cubiche\Core\Bus\Tests\Fixtures\Command\LogoutUserCommand;
use Cubiche\Core\Bus\Tests\Units\TestCase;
use Cubiche\Core\Validator\Exception\ValidationException;

/**
 * ValidatorMiddleware class.
 *
 * Generated by TestGenerator on 2016-04-11 at 15:18:25.
 */
class ValidatorMiddlewareTests extends TestCase
{
    /**
     * Test handle method.
     */
    public function testHandle()
    {
        $this
            ->given($middleware = new ValidatorMiddleware())
            ->and($command = new LoginUserCommand('ivan@cubiche.com', 'plainpassword'))
            ->and($callable = function (LoginUserCommand $command) {
                $command->setEmail('info@cubiche.org');
            })
            ->when($middleware->handle($command, $callable))
            ->then()
                ->string($command->email())
                    ->isEqualTo('info@cubiche.org')
        ;

        $this
            ->given($middleware = new ValidatorMiddleware())
            ->and($command = new LoginUserCommand('invalid.email.com', 'plainpassword'))
            ->and($callable = function () {
            })
            ->then()
                ->exception(function () use ($middleware, $command, $callable) {
                    $middleware->handle($command, $callable);
                })->isInstanceOf(ValidationException::class)
        ;

        $this
            ->given($middleware = new ValidatorMiddleware())
            ->and($command = new LogoutUserCommand('invalid.email.com'))
            ->and($callable = function (LogoutUserCommand $command) {
                $command->setEmail('info@cubiche.org');
            })
            ->when($middleware->handle($command, $callable))
            ->then()
                ->string($command->email())
                    ->isEqualTo('info@cubiche.org')
        ;
    }
}
