<?php

/**
 * This file is part of the Cubiche/EventSourcing component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Domain\EventSourcing\Tests\Units\Migrations\Store;

use Cubiche\Domain\EventSourcing\Migrations\Store\InMemoryMigrationStore;

/**
 * InMemoryMigrationStoreTests class.
 *
 * Generated by TestGenerator on 2016-08-31 at 15:14:45.
 */
class InMemoryMigrationStoreTests extends MigrationStoreTestCase
{
    /**
     * {@inheritdoc}
     */
    protected function createStore()
    {
        return new InMemoryMigrationStore();
    }
}
