<?php

/**
 * This file is part of the Cubiche/EventSourcing component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Domain\EventSourcing\Tests\Units\Migrations;

use Cubiche\Domain\EventSourcing\EventStore\InMemoryEventStore;
use Cubiche\Domain\EventSourcing\Migrations\MigratorWithSnapshot;
use Cubiche\Domain\EventSourcing\Migrations\Store\InMemoryMigrationStore;
use Cubiche\Domain\EventSourcing\Snapshot\InMemorySnapshotStore;

/**
 * MigratorWithSnapshotTests class.
 *
 * Generated by TestGenerator on 2016-10-06 at 17:03:40.
 */
class MigratorWithSnapshotTests extends MigratorTests
{
    /**
     * @return Migrator
     */
    protected function createMigrator()
    {
        return new MigratorWithSnapshot(
            $this->getClassMetadataFactory(),
            new InMemoryMigrationStore(),
            new InMemoryEventStore(),
            new InMemorySnapshotStore(),
            $this->migrationsDirectory
        );
    }
}
