<?php

/**
 * This file is part of the Cubiche/EventSourcing component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Domain\EventSourcing\Tests\Units\Migrations;

use Cubiche\Domain\EventSourcing\Tests\Units\TestCase;

/**
 * MigratorTests class.
 *
 * Generated by TestGenerator on 2016-08-10 at 10:18:25.
 */
class MigratorTests extends TestCase
{
    /**
     * Test class.
     */
    public function testClass()
    {
        // todo: Implement tests for this class.
    }
}
