language: php

sudo: false

php:
    - 5.5
    - 5.6
    - 7.0

install:
  - curl -s http://getcomposer.org/installer | php
  - COMPOSER_ROOT_VERSION=dev-master php composer.phar install --dev --no-interaction

script:
  - vendor/bin/atoum -c .atoum.travis.php +verbose
  