<?php

/**
 * This file is part of the Cubiche/EventBus component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Domain\EventBus\Tests\Units;

/**
 * EventBus class.
 *
 * Generated by TestGenerator on 2016-04-11 at 15:18:25.
 */
class EventBusTests extends TestCase
{
    /**
     * Test Emit method.
     */
    public function testEmit()
    {
        // todo: Implement testEmit().
    }

    /**
     * Test AddListener method.
     */
    public function testAddListener()
    {
        // todo: Implement testAddListener().
    }

    /**
     * Test RemoveListener method.
     */
    public function testRemoveListener()
    {
        // todo: Implement testRemoveListener().
    }

    /**
     * Test AddSubscriber method.
     */
    public function testAddSubscriber()
    {
        // todo: Implement testAddSubscriber().
    }

    /**
     * Test RemoveSubscriber method.
     */
    public function testRemoveSubscriber()
    {
        // todo: Implement testRemoveSubscriber().
    }

    /**
     * Test GetListeners method.
     */
    public function testGetListeners()
    {
        // todo: Implement testGetListeners().
    }

    /**
     * Test GetListenerPriority method.
     */
    public function testGetListenerPriority()
    {
        // todo: Implement testGetListenerPriority().
    }

    /**
     * Test HasListeners method.
     */
    public function testHasListeners()
    {
        // todo: Implement testHasListeners().
    }
}
