<?php

/**
 * This file is part of the Cubiche/EventBus component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Domain\EventBus\Tests\Units;

/**
 * Event class.
 *
 * Generated by TestGenerator on 2016-04-11 at 15:18:25.
 */
class EventTests extends TestCase
{
    /**
     * Test Name method.
     */
    public function testName()
    {
        // todo: Implement testName().
    }

    /**
     * Test Named method.
     */
    public function testNamed()
    {
        // todo: Implement testNamed().
    }

    /**
     * Test StopPropagation method.
     */
    public function testStopPropagation()
    {
        // todo: Implement testStopPropagation().
    }

    /**
     * Test IsPropagationStopped method.
     */
    public function testIsPropagationStopped()
    {
        // todo: Implement testIsPropagationStopped().
    }
}
