<?php

/**
 * This file is part of the Cubiche package.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Core\Bus\Tests\Units\Event;

use Cubiche\Core\Bus\Event\Event;
use Cubiche\Core\Bus\Event\EventInterface;
use Cubiche\Core\Bus\Tests\Units\TestCase;

/**
 * Event class.
 *
 * Generated by TestGenerator on 2016-04-11 at 15:18:25.
 */
class EventTests extends TestCase
{
    /**
     * Test create method.
     */
    public function testCreate()
    {
        $this
            ->given($event = new Event())
            ->then()
                ->object($event)
                    ->isInstanceOf(EventInterface::class)
        ;
    }
}
