<?php

/**
 * This file is part of the Cubiche/Console component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Core\Console\Tests\Units;

use Cubiche\Tests\TestCase as BaseTestCase;

/**
 * TestCase class.
 *
 * Generated by TestGenerator on 2016-06-20 at 07:48:32.
 */
abstract class TestCase extends BaseTestCase
{
}
