<?php

/**
 * This file is part of the Cubiche package.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Core\Validator\Tests\Units;

use Cubiche\Core\Validator\Assert;

/**
 * AssertTests class.
 *
 * Generated by TestGenerator on 2016-05-18 at 15:26:52.
 */
class AssertTests extends TestCase
{
    /**
     * Test create method.
     */
    public function testCreate()
    {
        $this
            ->given($validator = Assert::create())
            ->then()
                ->object($validator)
                    ->isInstanceOf(Assert::class)
        ;
    }
}
