<?php

/**
 * This file is part of the Cubiche/Command component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Domain\Command\Tests\Units\Middlewares\Handler\Locator;

use Cubiche\Domain\Command\Exception\NotFoundException;
use Cubiche\Domain\Command\Middlewares\Handler\Locator\InMemoryLocator;
use Cubiche\Domain\Command\Middlewares\Handler\Locator\LocatorInterface;
use Cubiche\Domain\Command\Tests\Fixtures\LoginUserCommand;
use Cubiche\Domain\Command\Tests\Fixtures\LoginUserCommandHandler;
use Cubiche\Domain\Command\Tests\Units\TestCase;

/**
 * InMemoryLocator class.
 *
 * Generated by TestGenerator on 2016-04-07 at 15:40:41.
 */
class InMemoryLocatorTests extends TestCase
{
    /**
     * Test Add method.
     */
    public function testAdd()
    {
        $this
            ->given($handler = new LoginUserCommandHandler())
            ->then()
                ->object($locator = new InMemoryLocator([LoginUserCommand::class => $handler]))
                    ->isInstanceOf(LocatorInterface::class)
        ;

        $this
            ->given($handler = new LoginUserCommandHandler())
            ->then()
                ->exception(function () use ($handler) {
                    new InMemoryLocator([255 => $handler]);
                })
                ->isInstanceOf(\InvalidArgumentException::class)
                ->exception(function () use ($handler) {
                    new InMemoryLocator([LoginUserCommand::class => 255]);
                })
                ->isInstanceOf(\InvalidArgumentException::class)

        ;
    }

    /**
     * Test Locate method.
     */
    public function testLocate()
    {
        $this
            ->given($handler = new LoginUserCommandHandler())
            ->and($locator = new InMemoryLocator([LoginUserCommand::class => $handler]))
            ->when($result = $locator->locate(LoginUserCommand::class))
            ->then()
                ->object($result)
                    ->isEqualTo($handler)
                ->exception(function () use ($locator) {
                    $locator->locate('Foo');
                })
                ->isInstanceOf(NotFoundException::class)
        ;
    }
}
