<?php

/**
 * This file is part of the Cubiche/Localizable component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Domain\Localizable\Tests\Units;

use Cubiche\Domain\Localizable\LocaleCode;
use Cubiche\Domain\Localizable\LocalizableString;
use Cubiche\Domain\Localizable\LocalizableValueMode;
use Cubiche\Domain\System\StringLiteral;

/**
 * LocalizableStringTests class.
 *
 * Generated by TestGenerator on 2018-01-15 at 13:40:07.
 */
class LocalizableStringTests extends TestCase
{
    /**
     * Test FromNative method.
     */
    public function testFromNative()
    {
        $this
            ->given($localizableString = LocalizableString::fromNative('Hello world'))
            ->when($constructedLocalizableString = new LocalizableString(LocaleCode::EN()))
            ->and($constructedLocalizableString->addNative('Hello world', LocaleCode::EN()))
            ->then()
                ->object($constructedLocalizableString)
                    ->isEqualTo($localizableString)
        ;
    }

    /**
     * Test AddNative method.
     */
    public function testAddNative()
    {
        $this
            ->given($localizableString = new LocalizableString(LocaleCode::EN()))
            ->when($localizableString->addNative('Hello world', LocaleCode::EN()))
            ->then()
                ->boolean($localizableString->has(LocaleCode::EN()))
                    ->isTrue()
                ->boolean($localizableString->value(LocaleCode::EN())->equals(new StringLiteral('Hello world')))
                    ->isTrue()
        ;
    }

    /**
     * Test Add method.
     */
    public function testAdd()
    {
        $this
            ->given($localizableString = new LocalizableString(LocaleCode::EN()))
            ->when($localizableString->add(new StringLiteral('Hello world'), LocaleCode::EN()))
            ->then()
                ->boolean($localizableString->has(LocaleCode::EN()))
                    ->isTrue()
                ->boolean($localizableString->value(LocaleCode::EN())->equals(new StringLiteral('Hello world')))
                    ->isTrue()
        ;
    }

    /**
     * Test ToNative method.
     */
    public function testToNative()
    {
        $this
            ->given($localizableString = new LocalizableString(LocaleCode::EN()))
            ->when($localizableString->addNative('Hello world', LocaleCode::EN()))
            ->then()
                ->string($localizableString->toNative())
                    ->isEqualTo('Hello world')
        ;
    }

    /**
     * Test Equals method.
     */
    public function testEquals()
    {
        $this
            ->given(
                $localizableString = new LocalizableString(LocaleCode::EN()),
                $localizableString->addNative('Hello world', LocaleCode::EN())
            )
            ->when(
                $localizableString1 = new LocalizableString(LocaleCode::EN()),
                $localizableString1->addNative('Hello world', LocaleCode::EN())
            )
            ->and(
                $localizableString2 = new LocalizableString(LocaleCode::EN()),
                $localizableString2->addNative('Good bye', LocaleCode::EN())
            )
            ->and(
                $localizableString3 = new LocalizableString(LocaleCode::ES(), LocalizableValueMode::STRICT()),
                $localizableString3->addNative('Hello world', LocaleCode::EN())
            )
            ->then()
                ->boolean($localizableString->equals($localizableString1))
                    ->isTrue()
                ->boolean($localizableString->equals($localizableString2))
                    ->isFalse()
                ->boolean($localizableString->equals($localizableString3))
                    ->isFalse()
        ;
    }

    /**
     * Test __toString method.
     */
    public function testToString()
    {
        $this
            ->given($localizableString = new LocalizableString(LocaleCode::EN()))
            ->then()
                ->string($localizableString->__toString())
                    ->isEqualTo('')
                ->and()
                ->when($localizableString->addNative('Hello world', LocaleCode::EN()))
                ->then()
                    ->string($localizableString->__toString())
                        ->isEqualTo('Hello world')
        ;
    }

    /**
     * Test Mode method.
     */
    public function testMode()
    {
        $this
            ->given($localizableString = new LocalizableString(LocaleCode::EN(), LocalizableValueMode::STRICT()))
            ->then()
                ->boolean($localizableString->mode()->equals(LocalizableValueMode::STRICT()))
                    ->isTrue()
        ;
    }

    /**
     * Test Mode method.
     */
    public function testStrictMode()
    {
        $this
            ->given($localizableString = new LocalizableString(LocaleCode::EN(), LocalizableValueMode::STRICT()))
            ->when($localizableString->addNative('Hola mundo', LocaleCode::ES()))
            ->then()
                ->variable($localizableString->toNative())
                    ->isNull()
        ;
    }

    /**
     * Test Mode method.
     */
    public function testAnyMode()
    {
        $this
            ->given($localizableString = new LocalizableString(LocaleCode::EN(), LocalizableValueMode::ANY()))
            ->when($localizableString->addNative('Hola mundo', LocaleCode::ES()))
            ->then()
                ->boolean($localizableString->locale()->equals(LocaleCode::ES()))
                    ->isTrue()
                ->string($localizableString->toNative())
                    ->isEqualTo('Hola mundo')
        ;

        $this
            ->given($localizableString = new LocalizableString(LocaleCode::FR(), LocalizableValueMode::ANY()))
            ->when($localizableString->addNative('Hello world', LocaleCode::EN()))
            ->and($localizableString->addNative('Hola mundo', LocaleCode::ES()))
            ->then()
                ->boolean($localizableString->locale()->equals(LocaleCode::EN()))
                    ->isTrue()
                ->string($localizableString->toNative())
                    ->isEqualTo('Hello world')
        ;

        $this
            ->given($localizableString = new LocalizableString(LocaleCode::FR(), LocalizableValueMode::ANY()))
            ->then()
                ->boolean($localizableString->locale()->equals(LocaleCode::FR()))
                    ->isTrue()
        ;
    }

    /**
     * Test SetMode method.
     */
    public function testSetMode()
    {
        $this
            ->given($localizableString = new LocalizableString(LocaleCode::EN(), LocalizableValueMode::STRICT()))
            ->when($localizableString->setMode(LocalizableValueMode::ANY()))
            ->then()
                ->boolean($localizableString->mode()->equals(LocalizableValueMode::ANY()))
                    ->isTrue()
        ;
    }

    /**
     * Test Locale method.
     */
    public function testLocale()
    {
        $this
            ->given($localizableString = new LocalizableString(LocaleCode::EN()))
            ->then()
                ->boolean($localizableString->locale()->equals(LocaleCode::EN()))
                    ->isTrue()
        ;
    }

    /**
     * Test SetLocale method.
     */
    public function testSetLocale()
    {
        $this
            ->given($localizableString = new LocalizableString(LocaleCode::EN()))
            ->when($localizableString->setLocale(LocaleCode::ES()))
            ->then()
                ->boolean($localizableString->locale()->equals(LocaleCode::ES()))
                    ->isTrue()
        ;
    }

    /**
     * Test Remove method.
     */
    public function testRemove()
    {
        $this
            ->given($localizableString = new LocalizableString(LocaleCode::EN()))
            ->when($localizableString->addNative('Hello world', LocaleCode::EN()))
            ->then()
                ->boolean($localizableString->has(LocaleCode::EN()))
                    ->isTrue()
                ->and()
                ->when($localizableString->remove(LocaleCode::EN()))
                ->then()
                    ->boolean($localizableString->has(LocaleCode::EN()))
                        ->isFalse()
        ;
    }

    /**
     * Test Has method.
     */
    public function testHas()
    {
        $this
            ->given($localizableString = new LocalizableString(LocaleCode::EN()))
            ->then()
                ->boolean($localizableString->has(LocaleCode::EN()))
                    ->isFalse()
                ->and()
                ->when($localizableString->addNative('Hello world', LocaleCode::EN()))
                ->then()
                    ->boolean($localizableString->has(LocaleCode::EN()))
                        ->isTrue()
        ;
    }

    /**
     * Test Translate method.
     */
    public function testTranslate()
    {
        $this
            ->given($localizableString = new LocalizableString(LocaleCode::EN()))
            ->when($localizableString->addNative('Hello world', LocaleCode::EN()))
            ->then()
                ->variable($localizableString->translate(LocaleCode::ES()))
                    ->isNull()
                ->array($localizableString->translations())
                    ->hasSize(1)
                ->and()
                ->when($localizableString->addNative('Hola mundo', LocaleCode::ES()))
                ->then()
                    ->array($localizableString->translations())
                        ->hasSize(2)
                    ->string($localizableString->translate(LocaleCode::EN()))
                        ->isEqualTo('Hello world')
                    ->string($localizableString->translate(LocaleCode::ES()))
                        ->isEqualTo('Hola mundo')
        ;
    }
}
