<?php

/**
 * This file is part of the Cubiche/System component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Domain\System\Tests\Units\DateTime;

use Cubiche\Core\Validator\Exception\InvalidArgumentException;
use Cubiche\Domain\System\DateTime\Month;
use Cubiche\Domain\System\Tests\Units\TestCase;

/**
 * MonthTests class.
 *
 * Generated by TestGenerator on 2018-01-15 at 13:37:53.
 */
class MonthTests extends TestCase
{
    /**
     * Test FromNative method.
     */
    public function testFromNative()
    {
        $this
            ->given($fromNativeMonth = Month::fromNative(Month::APRIL))
            ->and($month = new Month('April'))
            ->then()
            ->object($month)
            ->isEqualTo($fromNativeMonth)
            ->and()
            ->exception(function () {
                Month::fromNative('enero');
            })->isInstanceOf(InvalidArgumentException::class)
        ;
    }

    /**
     * Test FromNativeDateTime method.
     */
    public function testFromNativeDateTime()
    {
        $this
            ->given($dateTime = \DateTime::createFromFormat('Y-m-d H:i:s', '2015-04-13 15:05:20'))
            ->and($fromNativeMonth = Month::fromNativeDateTime($dateTime))
            ->and($month = new Month('April'))
            ->and($month7 = new Month(Month::JULY))
            ->then()
                ->object($month)
                    ->isEqualTo($fromNativeMonth)
                ->object($month7)
                    ->isNotEqualTo($fromNativeMonth)
        ;
    }

    /**
     * Test OrdinalValue method.
     */
    public function testOrdinalValue()
    {
        $this
            ->given($month = new Month('April'))
            ->and($month7 = new Month(Month::JULY))
            ->then()
                ->integer($month->ordinalValue())
                    ->isEqualTo(4)
                ->integer($month7->ordinalValue())
                    ->isEqualTo(7)
        ;
    }
}
