<?php

/**
 * This file is part of the Cubiche/Bus component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Infrastructure\Bus\Tests\Units\Middlewares\Handler\Locator;

use Cubiche\Core\Bus\Exception\NotFoundException;
use Cubiche\Core\Bus\Tests\Fixtures\Message\LoginUserMessage;
use Cubiche\Core\Bus\Tests\Fixtures\Message\LoginUserMessageListener;
use Cubiche\Core\Bus\Tests\Units\Middlewares\Handler\Locator\LocatorTestCase;
use Cubiche\Infrastructure\Bus\Middlewares\Handler\Locator\ContainerLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;

/**
 * ContainerLocatorTests class.
 *
 * Generated by TestGenerator on 2017-05-03 at 10:00:57.
 */
class ContainerLocatorTests extends LocatorTestCase
{
    /**
     * {@inheritdoc}
     */
    protected function createLocator()
    {
        $container = new ContainerBuilder();

        return new ContainerLocator($container);
    }

    /**
     * {@inheritdoc}
     */
    protected function createNonEmptyLocator()
    {
        $container = new ContainerBuilder();

        return new ContainerLocator($container);
    }

    /**
     * Test addHandler.
     */
    public function testAddHandler()
    {
        parent::testAddHandler();

        $this
            ->given($locator = $this->createLocator())
            ->and($handler = new LoginUserMessageListener())
            ->then()
                ->exception(function () use ($locator, $handler) {
                    $locator->addHandler(LoginUserMessage::class, $handler);
                })
                ->isInstanceOf(\InvalidArgumentException::class)
        ;
    }

    /**
     * Test Locate method.
     */
    public function testLocate()
    {
        $this
            ->given($locator = $this->createLocator())
            ->then()
                ->exception(function () use ($locator) {
                    $locator->locate(LoginUserMessage::class);
                })
                ->isInstanceOf(NotFoundException::class)
        ;

        $this
            ->given($container = new ContainerBuilder())
            ->and($container->register('app.login.handler', LoginUserMessageListener::class))
            ->and($locator = new ContainerLocator($container))
            ->when($locator->addHandler(LoginUserMessage::class, 'app.login.handler'))
            ->then()
                ->object($locator->locate(LoginUserMessage::class))
                ->isInstanceOf(LoginUserMessageListener::class)
                ->and()
                ->exception(function () use ($locator) {
                    $locator->locate('Foo');
                })
                ->isInstanceOf(NotFoundException::class)
        ;
    }
}
