<?php

/**
 * This file is part of the Cubiche/Command component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Domain\CommandBus\Tests\Units\Middlewares\Handler\Resolver\MethodName;

use Cubiche\Domain\CommandBus\Middlewares\Handler\Resolver\MethodName\MethodWithCommandNameResolver;
use Cubiche\Domain\CommandBus\Tests\Fixtures\LoginUserCommand;
use Cubiche\Domain\CommandBus\Tests\Units\TestCase;

/**
 * MethodWithCommandNameResolver class.
 *
 * Generated by TestGenerator on 2016-04-07 at 15:40:41.
 */
class MethodWithCommandNameResolverTests extends TestCase
{
    /**
     * Test Resolve method.
     */
    public function testResolve()
    {
        $this
            ->given($resolver = new MethodWithCommandNameResolver())
            ->when($result = $resolver->resolve(new LoginUserCommand('ivan@timeout.com', 'plainpassword')))
            ->then()
                ->string($result)
                    ->isEqualTo('handleLoginUserCommand')
        ;
    }
}
