<?php

/**
 * This file is part of the Cubiche/Storage component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Core\Storage\Tests\Units;

use Cubiche\Core\EventBus\Event\EventBus;
use Cubiche\Core\Serializer\Handler\HandlerManager;
use Cubiche\Core\Serializer\Serializer;
use Cubiche\Core\Serializer\Visitor\DeserializationVisitor;
use Cubiche\Core\Serializer\Visitor\SerializationVisitor;
use Cubiche\Core\Serializer\Visitor\VisitorNavigator;
use Cubiche\Tests\TestCase as BaseTestCase;

/**
 * TestCase class.
 *
 * Generated by TestGenerator on 2016-04-11 at 15:18:25.
 */
abstract class TestCase extends BaseTestCase
{
    use ClassMetadataFactoryTrait;

    /**
     * @return Serializer
     */
    protected function createSerializer()
    {
        $handlerManager = new HandlerManager();
        $eventBus = EventBus::create();

        $navigator = new VisitorNavigator($this->createFactory(), $handlerManager, $eventBus);
        $serializationVisitor = new SerializationVisitor($navigator);
        $deserializationVisitor = new DeserializationVisitor($navigator);

        return new Serializer($navigator, $serializationVisitor, $deserializationVisitor);
    }
}
