<?php

/**
 * This file is part of the Cubiche/EventSourcing component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Domain\EventSourcing\Tests\Units\EventStore;

use Cubiche\Domain\EventSourcing\EventStore\EventStream;
use Cubiche\Domain\EventSourcing\Tests\Fixtures\Event\PostWasCreated;
use Cubiche\Domain\EventSourcing\Tests\Units\TestCase;
use Cubiche\Domain\Model\Tests\Fixtures\PostId;

/**
 * EventStreamTests class.
 *
 * Generated by TestGenerator on 2016-06-28 at 14:36:54.
 */
class EventStreamTests extends TestCase
{
    /**
     * Test id method.
     */
    public function testId()
    {
        $this
            ->given($postId = PostId::fromNative(md5(rand())))
            ->and($eventStream = new EventStream($postId, []))
            ->then()
                ->object($eventStream->id())
                    ->isEqualTo($postId)
        ;
    }

    /**
     * Test Events method.
     */
    public function testEvents()
    {
        $this
            ->given($postId = PostId::fromNative(md5(rand())))
            ->and($eventStream = new EventStream($postId, []))
            ->then()
                ->array(iterator_to_array($eventStream->events()))
                    ->isEmpty()
        ;

        $this
            ->given($postId = PostId::fromNative(md5(rand())))
            ->and($eventStream = new EventStream($postId, [new PostWasCreated($postId, 'foo', 'bar')]))
            ->then()
                ->array(iterator_to_array($eventStream->events()))
                    ->hasSize(1)
        ;

        $this
            ->given($postId = PostId::fromNative(md5(rand())))
            ->then()
                ->exception(function () use ($postId) {
                    new EventStream($postId, ['bar']);
                })->isInstanceOf(\InvalidArgumentException::class)
        ;
    }
}
