<?php

/**
 * This file is part of the Cubiche/EventSourcing component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Domain\EventSourcing\Tests\Units\EventStore;

use Cubiche\Domain\EventSourcing\EventStore\InMemoryEventStore;

/**
 * InMemoryEventStoreTests class.
 *
 * Generated by TestGenerator on 2016-06-28 at 14:36:54.
 */
class InMemoryEventStoreTests extends EventStoreTestCase
{
    /**
     * {@inheritdoc}
     */
    protected function createStore()
    {
        return new InMemoryEventStore();
    }
}
