<?php

/**
 * This file is part of the Cubiche/ProcessManager component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Domain\ProcessManager\Tests\Units;

use Cubiche\Core\EventDispatcher\EventDispatcher;

/**
 * SettingEventDispatcher trait.
 *
 * Generated by TestGenerator on 2017-09-13 at 12:50:27.
 */
trait SettingEventDispatcherTrait
{
    /**
     * @var EventDispatcher
     */
    protected $eventDispatcher;

    /**
     * @return EventDispatcher
     */
    public function eventDispatcher()
    {
        if ($this->eventDispatcher === null) {
            $this->eventDispatcher = new EventDispatcher();

            foreach ($this->eventSubscribers() as $subscriber) {
                $this->eventDispatcher->addSubscriber($subscriber);
            }
        }

        return $this->eventDispatcher;
    }

    /**
     * @return array
     */
    abstract protected function eventSubscribers();
}
