<?php

/**
 * This file is part of the Cubiche/Serializer component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Core\Serializer\Tests\Units;

use Cubiche\Core\Serializer\DefaultSerializer;
use Cubiche\Core\Serializer\Tests\Fixtures\Address;
use Cubiche\Core\Serializer\Tests\Fixtures\Person;

/**
 * DefaultSerializer class.
 *
 * Generated by TestGenerator on 2016-05-03 at 14:37:10.
 */
class DefaultSerializerTests extends TestCase
{
    /**
     * Test serialize/deserialize method.
     */
    public function testSerializeDeserialize()
    {
        $this
            ->given($serializer = new DefaultSerializer())
            ->and($address = new Address('Avinguda Vilares, 5, Montgar', '08390', 'Barcelona'))
            ->and($person = new Person('Ivannis Suarez Jerez', $address))
            ->and($person1 = new Person('Carla Fernandez Couso', $address))
            ->when($data = $serializer->serialize($person, 'json'))
            ->then()
                ->boolean($person->equals($serializer->deserialize($data, 'Person', 'json')))
                    ->isTrue()
                ->boolean($person1->equals($serializer->deserialize($data, 'Person', 'json')))
                    ->isFalse()
        ;
    }
}
