<?php

/**
 * This file is part of the Cubiche package.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cubiche\Domain\EventSourcing\Tests\Units\Snapshot;

use Cubiche\Domain\EventSourcing\Snapshot\Snapshot;
use Cubiche\Domain\EventSourcing\Snapshot\SnapshotStoreInterface;
use Cubiche\Domain\EventSourcing\Tests\Fixtures\PostEventSourcedFactory;
use Cubiche\Domain\EventSourcing\Tests\Units\TestCase;
use Cubiche\Domain\EventSourcing\Versioning\Version;
use Cubiche\Domain\Model\Tests\Fixtures\PostId;

/**
 * SnapshotStoreTestCase class.
 *
 * Generated by TestGenerator on 2016-06-28 at 14:36:54.
 */
abstract class SnapshotStoreTestCase extends TestCase
{
    /**
     * @return SnapshotStoreInterface
     */
    abstract protected function createStore();

    /**
     * Test Persist method.
     */
    public function testPersist()
    {
        $this
            ->given($store = $this->createStore())
            ->and(
                $post = PostEventSourcedFactory::create(
                    $this->faker->sentence,
                    $this->faker->paragraph
                )
            )
            ->and($snapshot = new Snapshot('posts', $post, new \DateTime()))
            ->and($applicationVersion = Version::fromString('0.0.0'))
            ->when($store->persist($snapshot, $applicationVersion))
            ->then()
                ->object($store->load('posts', $post->id(), $post->version(), $applicationVersion))
                    ->isEqualTo($snapshot)
                ->and()
                ->when($applicationVersion = Version::fromString('2.0.0'))
                ->then()
                    ->variable($store->load('posts', $post->id(), $post->version(), $applicationVersion))
                        ->isNull()
        ;
    }

    /**
     * Test Load method.
     */
    public function testLoad()
    {
        $this
            ->given($store = $this->createStore())
            ->and(
                $post = PostEventSourcedFactory::create(
                    $this->faker->sentence,
                    $this->faker->paragraph
                )
            )
            ->and($snapshot = new Snapshot('posts', $post, new \DateTime()))
            ->and($applicationVersion = Version::fromString('1.1.0'))
            ->when($store->persist($snapshot, $applicationVersion))
            ->then()
                ->variable($store->load('blogs', $post->id(), $post->version(), $applicationVersion))
                    ->isNull()
                ->variable(
                    $store->load('posts', PostId::fromNative(md5(rand())), $post->version(), $applicationVersion)
                )->isNull()
        ;
    }

    /**
     * Test Remove method.
     */
    public function testRemove()
    {
        $this
            ->given($store = $this->createStore())
            ->and(
                $post = PostEventSourcedFactory::create(
                    $this->faker->sentence,
                    $this->faker->paragraph
                )
            )
            ->and($snapshot = new Snapshot('posts', $post, new \DateTime()))
            ->and($applicationVersion = Version::fromString('0.1.0'))
            ->when($store->persist($snapshot, $applicationVersion))
            ->and($store->remove('blogs', $post->id(), $post->version(), $applicationVersion))
            ->then()
                ->object($store->load('posts', $post->id(), $post->version(), $applicationVersion))
                    ->isEqualTo($snapshot)
                ->and()
                ->when($store->remove('posts', $post->id(), $post->version(), $applicationVersion))
                ->then()
                    ->variable($store->load('posts', $post->id(), $post->version(), $applicationVersion))
                        ->isNull()
        ;

        $this
            ->given($store = $this->createStore())
            ->and(
                $post = PostEventSourcedFactory::create(
                    $this->faker->sentence,
                    $this->faker->paragraph
                )
            )
            ->and($snapshot = new Snapshot('posts', $post, new \DateTime()))
            ->and($applicationVersion = Version::fromString('0.1.0'))
            ->when($store->persist($snapshot, $applicationVersion))
            ->then()
                ->object($store->load('posts', $post->id(), $post->version(), $applicationVersion))
                    ->isEqualTo($snapshot)
                ->and()
                ->when($applicationVersion2 = Version::fromString('2.0.0'))
                ->and($store->remove('posts', $post->id(), $post->version(), $applicationVersion2))
                ->then()
                    ->object($store->load('posts', $post->id(), $post->version(), $applicationVersion))
                        ->isEqualTo($snapshot)
                ->and()
                ->when($store->remove('posts', $post->id(), $post->version(), $applicationVersion))
                ->then()
                    ->variable($store->load('posts', $post->id(), $post->version(), $applicationVersion))
                        ->isNull()
        ;
    }
}
